### ISSUE TITLE
How to filter questions based on tf-idf before applying cosine similarity.

### ISSUE THREAD

**Issue by chaitu9701** [lior-k/fast-elasticsearch-vector-scoring#13]
How to filter questions based on tf-idf before applying cosine similarity.

In my elasticsearch each document has these fields. I have about 200000 such documents.

    question: What is the capital of China?
    answer : Beijing
    embedding vector: []
    client : 123  #(a unique id)

The issue i'm facing is that for eg for the above question, "What is the capital of China?", I get the averaged wordvectors using googles pretrained model(from word2vec). When I query "What is the capital of India?",it matches with the question "What is the capital of China?" with a similarity score of 1 and returns a wrong response. To solve this issue im trying to retrieve question by TF-Idf and then apply cosine similarity on that filtered query.

My mapping is as follows

    PUT /chat-history-old
    {
      "settings": {
        "analysis": {
          "filter": {
            "stop": {
              "type":"stop",
              "stopwords": [ "a","an","the","in","on"]
            },
            "synonym" : {
              "type" : "synonym",
              "synonyms" : [
    "pull_off, manage, cope, oversee, wangle, do, wield",
    "replace, supplant, substitute"]
            }
           },
          "analyzer": {
            "synonym" : {
              "tokenizer" : "whitespace",
                "filter": [
                "lowercase",
                "synonym",
                "stop"
    ]
              }
          }
        }
      },
      "mappings": {
        "doc": {
          "properties": {
            "question": {"type": "text",
                         "analyzer": "standard", 
                         "search_analyzer": "synonym"},
            "embedding_vector": {"type": "binary",
                                 "doc_values": true},
            "source_url":{ "type": "keyword" }
          }
        }
      }
    }

And my Query is as follows: I tried various versions of the below query but everything would give me a score of 1.00, can you help?

    PUT /chat-history-old
    {
      "mappings": {
        "doc": { 
          "properties": {
            "question": {"type": "nested"}, 
            "embedding_vector": {"type": "binary",
                             "doc_values": true},
            "source_url":    { "type": "keyword" }
          }
        }
      }
    }

**Comment by lior-k** [comment]
You can combine function_Scores, see example here: https://discuss.elastic.co/t/es-6-2-multiple-function-scores-boost-modes/127557
