### ISSUE TITLE
In 5.6.0 ，can't plugin ,how to fix it?

### ISSUE THREAD

**Issue by lornsky** [lior-k/fast-elasticsearch-vector-scoring#24]
bin/elasticsearch-plugin install /root/vector/target/releases/elasticsearch-binary-vector-scoring-5.6.0.zip

alert:
**ERROR: Unknown plugin /root/vector/target/releases/elasticsearch-binary-vector-scoring-5.6.0.zip**

how to fix it,thanks!

**Comment by lior-k** [comment]
Hi Yang guang,
were you able to install it?

**Comment by lornsky** [comment]
Yes, installed it successful!
but when i query it return the result is not right!   
embedding_vector use python to get base64 code, i don't know the reason!
can you Converting a vector to Base64 with php ? thanks!

**Comment by lior-k** [comment]
Not sure how to do it in PHP.
maybe something like this? (P.S it doesn't really work, but it may give you an idea)
```
$br = [ 1.1, 2.2, 3.3];
print_r($br);
$s = pack("f*", $br);
var_dump($s);
$enc = base64_encode($s);
var_dump($enc);


$dec = base64_decode($enc);
var_dump($dec);
$ar = unpack("f*", $dec);
var_dump($ar);
```

**Comment by lornsky** [comment]
Thanks replied!  
I have one Billion vectors( base word2vec have 300 Features), Can I use the plugin?  Can the plugin return result？  thanks again！

**Comment by lior-k** [comment]
Yes, the plug-in will return the proper KNN result

**Comment by lornsky** [comment]
ok，I try it！  Do you have some suggestions for ES config with one Billion vectors？ thanks！

**Comment by lior-k** [comment]
- Each shard should not pass 50GB of data.
- The more shards you have means you'll have better latency for each call.
But worse throughout. So it depends on your use case
