### ISSUE TITLE
Can not find 6.8.1 branch ?

### ISSUE THREAD

**Issue by thusinh1969** [lior-k/fast-elasticsearch-vector-scoring#28]
Sorry but I git clone the repository and cd into the directory and  run:
mvn package

Eveything went fine but I could not find the 6.8.1 version anywhere ? What do I have to do to get ElasticSearch compatible version I need ?

I am indeed running 6.8.1

Thanks,
Steve

**Comment by lior-k** [comment]
Please use the `es-6.8.1` branch. 
Meaning run `git checkout es-6.8.1` before running `mvn...`
