### ISSUE TITLE
Algorithm behind this plugin

### ISSUE THREAD

**Issue by snakeztc** [lior-k/fast-elasticsearch-vector-scoring#30]
I am curious about the algorithm behind this plugin in order to achieve fast speed. Does it implement any sort of approximate-nearest neighbour algorithms, OR it's actually compute scores over the entire corpus using brutal force and speeding up via low-level code implementation? Thanks!

**Comment by lior-k** [comment]
Good question. The answer: It's the later. Brute Force on the entire
corpus  using a low level Lucene API.
This is inorder to keep this minimal, so it'll serve as a base for other
algorithms like LSH, K-means or others to be built ontop.

Internally we use K-means to divide the corpus to 200 clusters and store
that information inside the ES document, so each has a vector and a cluster
number.
Next, When querying for knn vectors we search  only in the 20 most relevant
clusters (using ES filtered query). So basically we search only 10% of the
corpus

**Comment by snakeztc** [comment]
Thanks for the quick answer! Very useful.  I tried the plugin with 2 million vectors on a single node ES (vector size 600) it took about 4-5 seconds to return. Any ideas on how to speed up without implementing  an ANN?

**Comment by lior-k** [comment]
Split the Elasticsearch index to more shards.
Rule of thumb - more shards = lower latency (since the problem is reduced
to more workers) = lower throughput (since in any request you fire up more
Cores)

I would also normalize the vectors before indexing and during search time
call the plug-in with "cosine: false"

**Comment by snakeztc** [comment]
Thanks!
