### ISSUE TITLE
query size is ignored

### ISSUE THREAD

**Issue by adidier17** [lior-k/fast-elasticsearch-vector-scoring#31]
Thank you for the great plugin! I'm seeing some unexpected behavior where no matter what I set the query size to, the entire size of the index is returned in the hits. Using the python, my query is like so:
```
def img_q(vector):
    query = { 
                  "query": {
                    "function_score": 
                      {"boost_mode": "replace",
                      "script_score": {
                        "script": {
                          "source": "elasticsearch-binary-vector-scoring",
                          "lang": "knn",
                         "params": {
                            "cosine": True,
                            "field": "feature",
                            "vector":  vector
                    
                          }
                        }
                      }
                    }
                  },
                  "from": 0,
                  "size": 100
                }
    return query

res = es.search(index='maars', body=img_q(myvector))
```
And then res['hits']['total'] is always the number of vectors in the index. Any idea why that could be happening? Thank you!

**Comment by lior-k** [comment]
Glad to hear it :-)

I think this issue is related to this other issue:
https://github.com/lior-k/fast-elasticsearch-vector-scoring/issues/25
Try following up on the details there, and let me know if it works.

**Comment by adidier17** [comment]
Thanks!
