### ISSUE TITLE
How to support ES 7.5

### ISSUE THREAD

**Issue by snakeztc** [lior-k/fast-elasticsearch-vector-scoring#34]
I'm pretty new to ES. How can I modify this plugin to make it work on ES 7.5? Thanks!

**Comment by lior-k** [comment]
Hi Tony.
I created branch `es-7.5.0` for ES 7.5.0
try it out.

```
git checkout es-7.5.0
mvn clean install
```

**Comment by lior-k** [comment]
BTW - ES 7.2 and above has adopted the vector type & allow queries using cosine similarity.
check it out:
https://www.elastic.co/blog/text-similarity-search-with-vectors-in-elasticsearch

And if you feel so - compare it's performance to this plugin.

Thanks,
Lior

**Comment by snakeztc** [comment]
Great! Thanks. Will definitely do some comparison.
