### ISSUE TITLE
Create new branch for es-7.2.1

### ISSUE THREAD

**Issue by amedhat3** [lior-k/fast-elasticsearch-vector-scoring#35]
Hi,
We are using Elasticsearch 7.2.1 and we are trying out the plugin, so we created a fork for that here
https://github.com/amedhat3/fast-elasticsearch-vector-scoring/tree/es-7.2.1
Just basic configuration change for now.
and we would like to contribute it back, in case if anyone uses the same version

**Comment by lior-k** [comment]
Cool, just create a merge request

**Comment by lior-k** [comment]
Thanks for the MR. Merged to branch es-7.2.1.
Closing this issue
