### ISSUE TITLE
How to query for two vectors with different weights?

### ISSUE THREAD

**Issue by thereye** [lior-k/fast-elasticsearch-vector-scoring#37]
This plugin is great for me. I have two vectors: image_vector and text_vector, and I added this two vectors in my ES index. 

The question is how to query two vectors at the same time with different weight(since the image vector is more important than text vector)?  thanks very much!

**Comment by lior-k** [comment]
Hi @thereye, I'm glad this plug-in helps you.
Regarding your question, you can combine multiple functions in a function_score query. See this documentation: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html

Just wrap the script_score with "functions: [•••]" and then you can have multiple script_score with different boosts for each.

Hope this helps,
Lior.

**Comment by thereye** [comment]
> Hi @thereye, I'm glad this plug-in helps you.
> Regarding your question, you can combine multiple functions in a function_score query. See this documentation: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html
> 
> Just wrap the script_score with "functions: [•••]" and then you can have multiple script_score with different boosts for each.
> 
> Hope this helps,
> Lior.

Thanks for your reply, that helps me!
