### ISSUE TITLE
Scoring problem

### ISSUE THREAD

**Issue by visionbike** [lior-k/fast-elasticsearch-vector-scoring#4]
Hi,
I applied your plug-in for my IR system. however, I got some problem in result, the score is all 0 or too big but I don't where I am wrong. I use elasticsearch 5.6 and import data, create vector and base64 representation by python. The vector have 300 float elements
this is my mapping:

        "mappings": {
            "QA_PAIR": {
                "properties": {
                    "answer": {
                        "type": "text",
                        "fields": {
                            "keyword": {
                                "type": "keyword",
                                "ignore_above": 256
                            }
                        }
                    },
                    "embedding_vector": {
                        "type": "binary",
                        "doc_values": true
                    },
                    "field": {
                        "type": "text",
                        "fields": {
                            "keyword": {
                                "type": "keyword",
                                "ignore_above": 256
                            }
                        }
                    },
                    "id": {
                        "type": "long"
                    },
                    "question": {
                        "type": "text",
                        "fields": {
                            "keyword": {
                                "type": "keyword",
                                "ignore_above": 256
                            }
                        }
                    },
                    "vector": {
                        "type": "float"
                    }
                }
            }
        }

This is my POST request:
{"query": {
	"function_score": {
		"script_score": {
			"script": {
				"source": "binary_vector_score",
				"lang": "knn",
				"params": {
					"cosine": false,
					"field": "embedding_vector",
					"vector": [ 
        					-0.393664352595806, 
					        -0.0226647332310677, 
					        -0.00257770717144012, 
					        -0.0262848362326622, 
					        0.0157693792134523, 
					        0.021204886958003, 
					        -0.00300449808128178, 
					        -0.0353441946208477, 
					        -0.0108432853594422, 
					        -0.00832815747708082, 
					        -0.0334242396056652, 
					        0.0286900401115417, 
					        -0.0486984103918076, 
					        -0.0764514692127705, 
					        -0.098212705925107, 
					        -0.0188445895910263, 
					        -0.00867833849042654, 
					        -0.00819160416722298, 
					        0.00789748691022396, 
					        0.00992754753679037, 
					        0.00328949838876724, 
					        -0.0214207042008638, 
					        0.053695060312748, 
					        0.0114074740558863, 
					        0.018918838351965, 
					        -0.00494892848655581, 
					        0.0158535111695528, 
					        0.000340433209203184, 
					        -0.0416207760572433, 
					        0.00885819271206856, 
					        0.0203350558876991, 
					        0.0196341946721077, 
					        0.00805150344967842, 
					        0.0172809381037951, 
					        -0.0163073185831308, 
					        -0.0242628678679466, 
					        -0.0123006738722324, 
					        -0.0107043273746967, 
					        0.0132684763520956, 
					        0.0103193828836083, 
					        0.0209956336766481, 
					        0.0202617701143026, 
					        -0.00449958629906178, 
					        -0.0305256191641092, 
					        -0.011040105484426, 
					        0.00017193662642967, 
					        -0.00850920379161835, 
					        -0.00640081474557519, 
					        0.00420213444158435, 
					        -0.0274321790784597, 
					        -0.0123433945700526, 
					        0.0274937450885773, 
					        -0.0168586056679487, 
					        0.0176509246230125, 
					        -0.0169484633952379, 
					        0.0091985696926713, 
					        0.0104979490861297, 
					        -0.0262205079197884, 
					        -0.00236284523271024, 
					        -0.00904732383787632, 
					        -0.0107208713889122, 
					        -0.00682731717824936, 
					        0.00660926382988691, 
					        0.00560688180848956, 
					        -0.0247711259871721, 
					        -0.0190500840544701, 
					        0.00775287440046668, 
					        -0.0289954785257578, 
					        -0.00747184874489903, 
					        0.0193586144596338, 
					        0.0120802875608206, 
					        0.016206843778491, 
					        -0.0174826458096504, 
					        0.0147814601659775, 
					        0.017630135640502, 
					        -0.0204884801059961, 
					        -0.014909434132278, 
					        0.0196892376989126, 
					        -0.00302323698997498, 
					        -0.0090223103761673, 
					        0.01304164621979, 
					        -0.014606237411499, 
					        0.0423114001750946, 
					        0.00438828580081463, 
					        -0.0239541307091713, 
					        -0.00360357551835477, 
					        -0.0266071911901236, 
					        -0.0276379473507404, 
					        0.0115173496305943, 
					        0.0411788076162338, 
					        0.00390775268897414, 
					        0.00776109704747796, 
					        -0.0186252873390913, 
					        -0.0338746309280396, 
					        -0.00381790637038648, 
					        -0.0157410316169262, 
					        -0.00173758645541966, 
					        -0.0276267547160387, 
					        -0.0256764013320208, 
					        -0.0143972961232066, 
					        0.00422005029395223, 
					        0.00174226681701839, 
					        -0.00529280072078109, 
					        -0.00298483157530427, 
					        0.0237466674298048, 
					        -0.000381538906367496, 
					        0.0214440282434225, 
					        -0.00530762178823352, 
					        0.000689058564603329, 
					        -0.0125927813351154, 
					        -0.00102692015934736, 
					        -0.0095093185082078, 
					        0.00104711460880935, 
					        -0.0184073429554701, 
					        -0.0241216663271189, 
					        -0.00370215787552297, 
					        -0.0137345250695944, 
					        -0.0212880503386259, 
					        0.0143173299729824, 
					        -0.0115857478231192, 
					        -0.0470556654036045, 
					        0.0245862007141113, 
					        -0.0331159941852093, 
					        0.030479134991765, 
					        -0.0119145521894097, 
					        -0.0107079083099961, 
					        0.0156362932175398, 
					        0.00851063057780266, 
					        -0.0122106913477182, 
					        -0.0186388660222292, 
					        -0.0129399606958032, 
					        -0.00317808636464179, 
					        0.0182554833590984, 
					        0.0426450856029987, 
					        0.000623300904408097, 
					        -0.0300357472151518, 
					        -0.00161296606529504, 
					        -0.0180671066045761, 
					        -0.00666029332205653, 
					        0.00505791231989861, 
					        0.0265592858195305, 
					        0.0255843754857779, 
					        -0.0100457491353154, 
					        0.0253202132880688, 
					        -0.012139892205596, 
					        -0.0362259522080421, 
					        -0.0152987893670797, 
					        -0.0245484430342913, 
					        -0.00930904969573021, 
					        0.0191434323787689, 
					        -0.0159061457961798, 
					        -0.0140967750921845, 
					        0.0159904416650534, 
					        0.0179337114095688, 
					        0.0332022458314896, 
					        0.0305974595248699, 
					        -0.0322530381381512, 
					        0.0296993963420391, 
					        -0.0249535031616688, 
					        -0.0145818749442697, 
					        -0.00493068667128682, 
					        -0.0129649350419641, 
					        -0.00838589575141668, 
					        -0.00907904282212257, 
					        -0.0218371748924255, 
					        -0.00743792951107025, 
					        0.0131364790722728, 
					        -0.0295483488589525, 
					        0.0190455988049507, 
					        -0.0349388867616653, 
					        0.0131504293531179, 
					        -0.0179475024342537, 
					        -0.0248983968049288, 
					        -0.00160752714145929, 
					        -0.027133621275425, 
					        0.0055695753544569, 
					        -0.00650271447375417, 
					        -0.0160584971308708, 
					        -0.0184302050620317, 
					        -0.00805380754172802, 
					        0.0180833451449871, 
					        -0.0151601936668158, 
					        0.0300506465137005, 
					        0.00744215678423643, 
					        0.00804111268371344, 
					        -0.0188703071326017, 
					        0.0101022161543369, 
					        -0.0489775165915489, 
					        0.0232952125370502, 
					        -3.43503925250843e-05, 
					        0.0263597127050161, 
					        -0.00297580193728209, 
					        -0.0150877563282847, 
					        0.0113939428701997, 
					        -0.0141372494399548, 
					        0.00690645119175315, 
					        0.00420609675347805, 
					        -0.00289567932486534, 
					        -0.0260642115026712, 
					        0.023167734965682, 
					        -0.0119347721338272, 
					        -0.0317580290138721, 
					        -0.00838809460401535, 
					        0.014795234426856, 
					        0.00265358691103756, 
					        0.00478976033627987, 
					        -0.00687875179573894, 
					        -0.0365001782774925, 
					        -0.00282259122468531, 
					        0.0045535396784544, 
					        0.0161611028015614, 
					        -0.0309465117752552, 
					        -0.0457352623343468, 
					        -0.00723987026140094, 
					        0.0160336326807737, 
					        -0.0495293997228146, 
					        -0.0121549246832728, 
					        -0.0176614001393318, 
					        0.0323552377521992, 
					        -0.0234786756336689, 
					        0.0126905748620629, 
					        -0.0129129076376557, 
					        -0.0250209085643291, 
					        -0.0159870591014624, 
					        0.0168980434536934, 
					        -0.00574642140418291, 
					        -0.0127127803862095, 
					        -0.0235360134392977, 
					        0.0177464168518782, 
					        -0.0410195142030716, 
					        0.0124300876632333, 
					        -0.0408283472061157, 
					        -0.00202183122746646, 
					        0.0129581457003951, 
					        0.00769506394863129, 
					        0.0152833797037601, 
					        0.00773142138496041, 
					        0.0372184813022614, 
					        -0.00283751101233065, 
					        0.0116243157535791, 
					        0.0340076796710491, 
					        -0.0178979858756065, 
					        0.00190313707571477, 
					        0.0128652043640614, 
					        0.0319913737475872, 
					        0.0199989080429077, 
					        0.00583306839689612, 
					        0.0433395206928253, 
					        -0.00441714935004711, 
					        -0.0122670559212565, 
					        0.00676291109994054, 
					        -0.00459515443071723, 
					        -0.0100066177546978, 
					        -0.028498774394393, 
					        0.00900082103908062, 
					        0.0115390392020345, 
					        0.0213581789284945, 
					        -0.021892013028264, 
					        -0.0315549038350582, 
					        -0.00541313784196973, 
					        0.00368455122224987, 
					        0.0329747684299946, 
					        -0.0160139333456755, 
					        0.0159961935132742, 
					        -0.0186245664954185, 
					        0.012709497474134, 
					        -0.00321295321919024, 
					        -0.03536007553339, 
					        -0.00312552158720791, 
					        -0.00993746519088745, 
					        0.0135975889861584, 
					        0.0121281202882528, 
					        0.0401832796633244, 
					        -0.0233429968357086, 
					        -0.0272878929972649, 
					        -0.00900955405086279, 
					        -0.0143176056444645, 
					        0.0258419327437878, 
					        -0.0159984435886145, 
					        0.00148292630910873, 
					        -0.0245296824723482, 
					        -0.0071764518506825, 
					        -0.0401290319859982, 
					        -0.0263967737555504, 
					        0.010935009457171, 
					        -0.0164317842572927, 
					        -0.0263612680137157, 
					        0.00294899567961693, 
					        0.00230222591198981, 
					        0.000246382056502625, 
					        -0.0147611405700445, 
					        -0.0356217697262764, 
					        -0.0434923432767391, 
					        -0.00176502345129848, 
					        -0.034493625164032, 
					        -0.0177724678069353, 
					        0.00524684647098184, 
					        0.0187848526984453, 
					        -0.00780178792774677, 
					        -0.00951886456459761]
				}
			}
		}
	}
},"size": 2
}

The result:
 {
                "_score": 0,
                "_source": {
                    "id": 1,
               ...
            },
            {
                "_score": 0,
                "_source": {
                    "id": 2,
               ...
                }
Please help me, I don't know why.
Thanks

**Comment by lior-k** [comment]
Hi there.
Try to submit the request with {cosine: true} instead of false.

**Comment by visionbike** [comment]
Hi,
I had changed cosine value but it didn't worked. I noticed that when I
packaged the plugin, it showed a warning:
 The following patterns were never triggered in this artifact exclusion
filter:
o  'org.elasticsearch:elasticsearch'
o  'org.apache.lucene:*'
I think this is problem, but I am just a newbie in java so I don't know how
to solve this.
Thanks,
Phuc

2018-03-30 0:52 GMT+07:00 lior-k <notifications@github.com>:

> Hi there.
> Try to submit the request with {cosine: true} instead of false.
>

**Comment by visionbike** [comment]
I used this for query in elasticsearch 5.6.0 (because your example query on github got error)
{
"query" : {
    "function_score" : {
        "boost_mode" : "replace",
        "script_score" : {
           "script" : {
        		"lang" : "knn",
        		"params" : {
            		"cosine" : true,
            		"field" : "embedding_vector",
            		"vector" : [0.2, 0.1, -0.05]},
            	"source": "binary_vector_score"}
        	}
    	}
	},
    "size": 2
}

**Comment by visionbike** [comment]
Great! Thank you so much! I'll try it.

**Comment by wangxiaxiaxia** [comment]
@visionbike 
Hi,I met a problem,expect for your soultion.
when I give a query body in Python as following:
```
{"query": {
"function_score": {
"script_score": {
"script": {
"source": "binary_vector_score",
"lang": "knn",
"params": {
"cosine": false,
"field": "embedding_vector",
"vector":MY_VECTOR
}}
```

but it got a error as:

> elasticsearch.exceptions.RequestError: TransportError(400, 'search_phase_execution_exception', 'script_score: the script could not be loaded')

What can I do? Do I miss some configure operation?
