### ISSUE TITLE
Read string field for Document

### ISSUE THREAD

**Issue by KTOIA** [lior-k/fast-elasticsearch-vector-scoring#41]
Hi, Lior. I would like to make a similarity search, not for a vector of a number, but for a vector of objects  (with a name for each of numbers: `[{"name":"a", "value": 0.42},{"name":"b", "value": 0.52}]`), is any way to read string value like BinaryDocValues way?

**Comment by lior-k** [comment]
No. The plugin expects a comma separated list of floats after it decodes
the Base64 embedding.

**Comment by KTOIA** [comment]
Yes, I understand, that current implementation doesn't support this approach, but maybe you know, how to read a string field. I only found the way to get the whole document as a string and convert it to Object, but it dramatically inefficient.

**Comment by KTOIA** [comment]
I found: 
`leafContext.reader().getSortedSetDocValues(fieldName);`
It's good for me, thank you for your quick answer!
