### ISSUE TITLE
Question: Score on multiple vectors

### ISSUE THREAD

**Issue by coreation** [lior-k/fast-elasticsearch-vector-scoring#49]
Hi @lior-k ,

first of all, many thanks for maintaining this plugin, I haven't tried it yet but it's something we were about to code ourselves. 
I just had a question with regards to comparing documents to multiple vectors and how that would work, I presume through a fork or even something you might want to merge into the code base.

Going by the code, I think the main thing to changes is in [this function](https://github.com/lior-k/fast-elasticsearch-vector-scoring/blob/master/src/main/java/com/liorkn/elasticsearch/script/VectorScoreScript.java#L140) where the value that is fetched is then treated as an array of vectors, on which the calculations are then performed, instead of the just the 1 vector that is now used... Is that correct and if so, is that something you might want to merge if/when we make the code change in a fork?

Keep up the good work!

**Comment by lior-k** [comment]
Hi, thanks for being interested. I'm glad the plugin can be of use for you, and that might be a good edition, as long as it will not affect latency or throughput.

Your idea sounds interesting. I'm especially interested in your use-case, can you share it?
 
How many vectors do you think

**Comment by coreation** [comment]
Hi @lior-k good point on the latency and throughput, I have no idea so far on what the effect will be.
Our use case is probably limited to a relatively low number of vectors (ranging from 3-20ish) vectors, which is I can imagine quite a big deal in terms of compute... so I'm cautious to call it a low amount in retrospect ^^.

The use case we want build is to return documents that match several pieces of text. Those pieces of text are sometimes already embedded, but can be search queries as well. The embedding isn't an issue, we have our models ready, but scaling the similarity search is what we want to use Elastic for.

For example, return all documents that match a general research question, but also take into account "starred" documents. In a twitter example you would search for tweets matching a certain piece of text, but also take into account tweets the user has already marked as "favorite". In our use case documents are mostly larger pieces of text like papers, patents and news content. 

Does that explain the use case for you?

**Comment by lior-k** [comment]
Interesting. In our company we included all the words and features needed
for matching in a single vector.

Let's say we have multiple vectors as input, but the output can be only 1
score - this is just how ES works. What should that score be - an average
of all, or maybe a weighted average?

**Comment by coreation** [comment]
hi @lior-k indeed ES works on a 1 score basis, but as you rightly figured out, the score would be a simple average, weighted avg, ... whatever works for us. The main reason why we're not concatenating all of our pieces of text a search must be similar to, is that those pieces can vary (heavily) in size, making it so that the resulting vector could make it so that less or worse results are returned. It's something we need to try out and see :)

On a different note, I've tried the code and it seems to be working fine, we do have in our index documents that have no embedding, am I correct to say that will mess up the results? From first tries it looks like it does, I've seen in other issues and the README that the field must be there, but does every document need an embedding value or can they be empty for it to work?

**Comment by lior-k** [comment]
Yes. The plugin by design expects the vector to be there and to be in the
correct size.
We chose that in order to show up bugs in documents or queries.
We might just add a "strict" vs. "non-strict" mode as parameter in the
query.

**Comment by coreation** [comment]
Ok, that makes sense, I'll make fork and see where I end up. If I can do it with a parameter so that it can be part of this code base, I won't hesitate to do so. Thanks so much for being so responsive!

**Comment by coreation** [comment]
@lior-k the new developments [on ElasticSearch 7.x](https://www.elastic.co/guide/en/elasticsearch/reference/master/dense-vector.html), are they implementing the same thing? I see on their blogposts that searching (scoring) through similarity is still on ongoing thing that they're looking to expand, but is this repository in essentially doing the same that Elastic is doing in 7.x?

**Comment by lior-k** [comment]
I think so, though I haven't compared it personally

**Comment by coreation** [comment]
Thanks for all the help so far @lior-k , based on what this repository is meant for (1-1 vector comparison) we decided to just start from scratch. We needed 4 different comparable parts with different weights to them in order to make things work for our use case, in my opinion that's far from what this repository is aiming to do. 

So I'll close this issue with a big thanks for your open source work!
