### ISSUE TITLE
es 5.6.3

### ISSUE THREAD

**Issue by xiaer1** [lior-k/fast-elasticsearch-vector-scoring#9]
hello，my es version is 5.6.3,how can I build it.
expect for you reply. thanks

**Comment by lior-k** [comment]
Hi there,
I suppose changing 5.6.0 in all files to 5.6.3 + mvn clean install should do the trick.

Please try it & let me know how it goes.

if it works Issue a pull request

**Comment by wangxiaxiaxia** [comment]
thanks for your reply,I will try it.

**Comment by wangxiaxiaxia** [comment]
Hi, I have tried it,but I got a error. What can I do?
`ERROR: This plugin was built with an older plugin structure. Contact the plugin author to remove the intermediate "elasticsearch" directory within the plugin zip.`

**Comment by wangxiaxiaxia** [comment]
Oh，sad. I use python3 to get query result(my query body is same as your),but I got a error 

> elasticsearch.exceptions.RequestError: TransportError(400, 'search_phase_execution_exception', 'script_score: the script could not be loaded')
it means I don't have the script, what can I do?expect for your reply.

**Comment by lior-k** [comment]
I'm testing this.
A few questions:
1. What's the ES version? Where you able to compile and install on ES 5.6.3?
2. Share the ES log here
3. Share you index mapping, a sample doc and the exact query url + body

**Comment by wangxiaxiaxia** [comment]
@lior-k Hi,thank you for you reply.I will give you more details
Firstly,I build it on ES 5.6.3 without any problem,just as you said: 
1.changing 5.6.0 in all files to 5.6.3 
2.then  mvn clean install   
lucky,that's OK.

Secondly,I use python to excute : create index,query operation,**my mapping is following:**

```
 _index_mappings = {
            "mappings": {
                self.index_type: {
                    "properties": {
                        "id": {
                            "type": "long",
                            "index": "true"
                        },
                        "embedding_vector": {
                            "type": "binary",
                            "doc_values": "true"
                        }
                    }
                }
            }
        }
```
**my query body is same as your example:**

```
doc_combine = {
              "query": {
                "function_score": {
                  "boost_mode": "replace",
                  "script_score": {
                    "script": {
                      "source": "binary_vector_score",
                      "lang": "knn",
                      "params": {
                        "cosine": "false",
                        "field": "embedding_vector",
                        "vector": MY_VECTOR
                      }
                    }
                  }
                }
              },
              "sort": {
		             "_score": {
                         "order": "desc"
                     }
              },
              "size": 10
            }
```
MY_VECTOR is like [0.23518182337284088,-0.0005498990649357438,-0.4127366542816162......]

**Thirdly,this is my ES startup logs:**

> [2018-07-26T09:12:25,811][INFO ][o.e.n.Node               ] [] initializing ...
> [2018-07-26T09:12:25,916][INFO ][o.e.e.NodeEnvironment    ] [AzRe5hv] using [1] data paths, mounts [[/ (/dev/mapper/ubuntu--vg-root)]], net usable_space [681.9gb], net total_space [900.6gb], spins? [possibly], types [ext4]
> [2018-07-26T09:12:25,917][INFO ][o.e.e.NodeEnvironment    ] [AzRe5hv] heap size [1.9gb], compressed ordinary object pointers [true]
> [2018-07-26T09:12:25,925][INFO ][o.e.n.Node               ] node name [AzRe5hv] derived from node ID [AzRe5hvcRkuz9s3sj-FzbA]; set [node.name] to override
> [2018-07-26T09:12:25,925][INFO ][o.e.n.Node               ] version[5.6.3], pid[7145], build[1a2f265/2017-10-06T20:33:39.012Z], OS[Linux/4.15.0-29-generic/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_171/25.171-b11]
> [2018-07-26T09:12:25,926][INFO ][o.e.n.Node               ] JVM arguments [-Xms2g, -Xmx2g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -Djdk.io.permissionsUseCanonicalPath=true, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Dlog4j.skipJansi=true, -XX:+HeapDumpOnOutOfMemoryError, -Des.path.home=/home/zmd/elasticsearch-5.6.3]
> [2018-07-26T09:12:26,458][INFO ][o.e.p.PluginsService     ] [AzRe5hv] loaded module [aggs-matrix-stats]
> [2018-07-26T09:12:26,458][INFO ][o.e.p.PluginsService     ] [AzRe5hv] loaded module [ingest-common]
> [2018-07-26T09:12:26,458][INFO ][o.e.p.PluginsService     ] [AzRe5hv] loaded module [lang-expression]
> [2018-07-26T09:12:26,458][INFO ][o.e.p.PluginsService     ] [AzRe5hv] loaded module [lang-groovy]
> [2018-07-26T09:12:26,458][INFO ][o.e.p.PluginsService     ] [AzRe5hv] loaded module [lang-mustache]
> [2018-07-26T09:12:26,458][INFO ][o.e.p.PluginsService     ] [AzRe5hv] loaded module [lang-painless]
> [2018-07-26T09:12:26,458][INFO ][o.e.p.PluginsService     ] [AzRe5hv] loaded module [parent-join]
> [2018-07-26T09:12:26,459][INFO ][o.e.p.PluginsService     ] [AzRe5hv] loaded module [percolator]
> [2018-07-26T09:12:26,459][INFO ][o.e.p.PluginsService     ] [AzRe5hv] loaded module [reindex]
> [2018-07-26T09:12:26,459][INFO ][o.e.p.PluginsService     ] [AzRe5hv] loaded module [transport-netty3]
> [2018-07-26T09:12:26,459][INFO ][o.e.p.PluginsService     ] [AzRe5hv] loaded module [transport-netty4]
> [2018-07-26T09:12:26,459][INFO ][o.e.p.PluginsService     ] [AzRe5hv] loaded plugin [elasticsearch-binary-vector-scoring]
> [2018-07-26T09:12:27,467][INFO ][o.e.d.DiscoveryModule    ] [AzRe5hv] using discovery type [zen]
> [2018-07-26T09:12:27,873][INFO ][o.e.n.Node               ] initialized
> [2018-07-26T09:12:27,873][INFO ][o.e.n.Node               ] [AzRe5hv] starting ...
> [2018-07-26T09:12:27,960][INFO ][o.e.t.TransportService   ] [AzRe5hv] publish_address {127.0.0.1:9300}, bound_addresses {[::1]:9300}, {127.0.0.1:9300}
> [2018-07-26T09:12:31,008][INFO ][o.e.c.s.ClusterService   ] [AzRe5hv] new_master {AzRe5hv}{AzRe5hvcRkuz9s3sj-FzbA}{j6UjXGRjRo2Bc16iMTfeYQ}{127.0.0.1}{127.0.0.1:9300}, reason: zen-disco-elected-as-master ([0] nodes joined)
> [2018-07-26T09:12:31,028][INFO ][o.e.h.n.Netty4HttpServerTransport] [AzRe5hv] publish_address {127.0.0.1:9200}, bound_addresses {[::1]:9200}, {127.0.0.1:9200}
> [2018-07-26T09:12:31,028][INFO ][o.e.n.Node               ] [AzRe5hv] started
> [2018-07-26T09:12:31,212][INFO ][o.e.g.GatewayService     ] [AzRe5hv] recovered [1] indices into cluster_state
> [2018-07-26T09:12:32,066][INFO ][o.e.c.r.a.AllocationService] [AzRe5hv] Cluster health status changed from [RED] to [YELLOW] (reason: [shards started [[mihui][2]] ...]).
> 

this is my error logs when I excute a query in Python:

```

> [2018-07-26T09:18:14,815][DEBUG][o.e.a.s.TransportSearchAction] [AzRe5hv] [mihui][2], node[AzRe5hvcRkuz9s3sj-FzbA], [P], s[STARTED], a[id=HlKXhKzfTe6KBx3arIhVVw]: Failed to execute [SearchRequest{searchType=QUERY_THEN_FETCH, indices=[], indicesOptions=IndicesOptions[id=38, ignore_unavailable=false, allow_no_indices=true, expand_wildcards_open=true, expand_wildcards_closed=false, allow_alisases_to_multiple_indices=true, forbid_closed_indices=true], types=[], routing='null', preference='null', requestCache=null, scroll=Scroll{keepAlive=5m}, maxConcurrentShardRequests=5, batchedReduceSize=512, preFilterShardSize=128, source={
>   "size" : 1000,
>   "query" : {
>     "function_score" : {
>       "query" : {
>         "match_all" : {
>           "boost" : 1.0
>         }
>       },
>       "functions" : [
>         {
>           "filter" : {
>             "match_all" : {
>               "boost" : 1.0
>             }
>           },
>           "script_score" : {
>             "script" : {
>               "source" : "binary_vector_score",
>               "lang" : "knn",
>               "params" : {
>                 "field" : "embedding_vector",
>                 "cosine" : "false",
>                 "vector" : [
>                   0.23518182337284088,
>                   -5.498990649357438E-4,
>                   -0.4127366542816162,
>                   0.6281453967094421,
>                 ...........
>                 ]
>               }
>             }
>           }
>         }
>       ],
>       "score_mode" : "multiply",
>       "boost_mode" : "replace",
>       "max_boost" : 3.4028235E38,
>       "boost" : 1.0
>     }
>   },
>   "sort" : [
>     {
>       "_doc" : {
>         "order" : "asc"
>       }
>     }
>   ]
> }}] lastShard [true]
> org.elasticsearch.transport.RemoteTransportException: [AzRe5hv][127.0.0.1:9300][indices:data/read/search[phase/query]]
> Caused by: org.elasticsearch.index.query.QueryShardException: **_script_score: the script could not be loaded_**
> 	at org.elasticsearch.index.query.functionscore.ScriptScoreFunctionBuilder.doToFunction(ScriptScoreFunctionBuilder.java:100) ~[elasticsearch-5.6.3.jar:5.6.3]
> 	at org.elasticsearch.index.query.functionscore.ScoreFunctionBuilder.toFunction(ScoreFunctionBuilder.java:137) ~[elasticsearch-5.6.3.jar:5.6.3]
> 	at org.elasticsearch.index.query.functionscore.FunctionScoreQueryBuilder.doToQuery(FunctionScoreQueryBuilder.java:304) ~[elasticsearch-5.6.3.jar:5.6.3]
> 	at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:96) ~[elasticsearch-5.6.3.jar:5.6.3]
> 	at org.elasticsearch.index.query.QueryShardContext.lambda$toQuery$1(QueryShardContext.java:313) ~[elasticsearch-5.6.3.jar:5.6.3]
> 	at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:325) ~[elasticsearch-5.6.3.jar:5.6.3]
> 	at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:312) ~[elasticsearch-5.6.3.jar:5.6.3]
> 	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:617) ~[elasticsearch-5.6.3.jar:5.6.3]
> 	at org.elasticsearch.search.SearchService.createContext(SearchService.java:485) ~[elasticsearch-5.6.3.jar:5.6.3]
> 	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:461) ~[elasticsearch-5.6.3.jar:5.6.3]
> 	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:257) ~[elasticsearch-5.6.3.jar:5.6.3]
> 	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:343) ~[elasticsearch-5.6.3.jar:5.6.3]
> 	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:340) ~[elasticsearch-5.6.3.jar:5.6.3]
> 	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-5.6.3.jar:5.6.3]
> 	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:644) [elasticsearch-5.6.3.jar:5.6.3]
> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638) [elasticsearch-5.6.3.jar:5.6.3]
> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.6.3.jar:5.6.3]
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
> Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
> 	at com.liorkn.elasticsearch.script.VectorScoreScript.<init>(VectorScoreScript.java:111) ~[?:?]
> 	at com.liorkn.elasticsearch.script.VectorScoreScript$Factory.newScript(VectorScoreScript.java:89) ~[?:?]
> 	at com.liorkn.elasticsearch.service.VectorScoringScriptEngineService.search(VectorScoringScriptEngineService.java:61) ~[?:?]
> 	at org.elasticsearch.script.ScriptService.search(ScriptService.java:500) ~[elasticsearch-5.6.3.jar:5.6.3]
> 	at org.elasticsearch.script.ScriptService.search(ScriptService.java:492) ~[elasticsearch-5.6.3.jar:5.6.3]
> 	at org.elasticsearch.index.query.QueryShardContext.getSearchScript(QueryShardContext.java:345) ~[elasticsearch-5.6.3.jar:5.6.3]
> 	at org.elasticsearch.index.query.functionscore.ScriptScoreFunctionBuilder.doToFunction(ScriptScoreFunctionBuilder.java:97) ~[elasticsearch-5.6.3.jar:5.6.3]
> 	at org.elasticsearch.index.query.functionscore.ScoreFunctionBuilder.toFunction(ScoreFunctionBuilder.java:137) ~[elasticsearch-5.6.3.jar:5.6.3]
> 	at org.elasticsearch.index.query.functionscore.FunctionScoreQueryBuilder.doToQuery(FunctionScoreQueryBuilder.java:304) ~[elasticsearch-5.6.3.jar:5.6.3]
> 	at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:96) ~[elasticsearch-5.6.3.jar:5.6.3]
> 	at org.elasticsearch.index.query.QueryShardContext.lambda$toQuery$1(QueryShardContext.java:313) ~[elasticsearch-5.6.3.jar:5.6.3]
> 	at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:325) ~[elasticsearch-5.6.3.jar:5.6.3]
> 	at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:312) ~[elasticsearch-5.6.3.jar:5.6.3]
> 	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:617) ~[elasticsearch-5.6.3.jar:5.6.3]
> 	at org.elasticsearch.search.SearchService.createContext(SearchService.java:485) ~[elasticsearch-5.6.3.jar:5.6.3]
> 	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:461) ~[elasticsearch-5.6.3.jar:5.6.3]
> 	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:257) ~[elasticsearch-5.6.3.jar:5.6.3]
> 	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:343) ~[elasticsearch-5.6.3.jar:5.6.3]
> 	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:340) ~[elasticsearch-5.6.3.jar:5.6.3]
> 	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-5.6.3.jar:5.6.3]
> 	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:644) ~[elasticsearch-5.6.3.jar:5.6.3]
> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638) ~[elasticsearch-5.6.3.jar:5.6.3]
> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-5.6.3.jar:5.6.3]
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_171]
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_171]
> 	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_171]

```
Addition,In /config/elasticsearch.yml ,I add as following:
```
script.inline: on

script.engine.groovy.inline.aggs: on

script.stored: on

script.file: on
```
that's all,Do I miss some other operation. 
**So I have a question,Should I write a script name as "binary_vector_score"?and where does it put?**
expect for you reply.

**Comment by lior-k** [comment]
Good news. Can you issue a PR on a different branch for sypporting es5.6.3?
